In [1]:
# Does not need to be executed if ~/.ipython/profile_default/ipython_config.py
# exists and contains get_config().InteractiveShell.ast_node_interactivity = 'all'

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [88]:
import string
dir(string)
dir('string')

['Formatter',
 'Template',
 '_ChainMap',
 '_TemplateMetaclass',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_re',
 '_string',
 'ascii_letters',
 'ascii_lowercase',
 'ascii_uppercase',
 'capwords',
 'digits',
 'hexdigits',
 'octdigits',
 'printable',
 'punctuation',
 'whitespace']

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [5]:
'***'.join('hello')
'abd cde aak'.partition(' ')
'1, 2, 3'.split(',')

'h***e***l***l***o'

('abd', ' ', 'cde aak')

['1', ' 2', ' 3']

In [10]:
# sorting, reversing
L = [3, 2, 1]
L.sort()   # sorts in place
L
L.reverse()   # reverses in place
L
print("---")
sorted(L)   # This creates a copy
L
a = reversed(L)   # creates a generator
L
for i in a:
    print(i)

[1, 2, 3]

[3, 2, 1]

---


[1, 2, 3]

[3, 2, 1]

[3, 2, 1]

1
2
3


In [22]:
str1 = "Hello, World! My name is John Smith."
str1.find("W", 0, 10)
str1.find("We", 0, 10)   # returns -1 if can't be found
str1.index("W", 0, 10)
str1.index("We", 0, 10)   # returns ValueError if can't be found

7

-1

7

ValueError: substring not found

In [8]:
str2 = 'ha  ha '
list(str2)
sorted(str2)
str2.split()

['h', 'a', ' ', ' ', 'h', 'a', ' ']

[' ', ' ', ' ', 'a', 'a', 'h', 'h']

['ha', 'ha']

In [92]:
'{0}, {1}, {2}'.format('a', 'b', 'c')
var1 = 1
f'{var1}'
f'{var1:>10}'   # right aligned
f'{var1:<10}'   # left aligned
f'{var1:^10}'   # centered
f'{var1:*^10}'   # centered
f'{var1:*=10}'   # padding

'a, b, c'

'1'

'         1'

'1         '

'    1     '

'****1*****'

'*********1'

In [95]:
# to get an iterator, you need to call iter() first
r1 = range(5, 15)
next(iter(r1))
next(iter(r1))
i = iter(r1)
next(i)
next(i)
next(i)
i

5

5

5

6

7

<div class="alert alert-info" style="font-size:150%">collections Module</div>

In [30]:
import collections

In [91]:
dir(collections.Counter)

['__add__',
 '__and__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__isub__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__missing__',
 '__module__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__weakref__',
 '_keep_positive',
 'clear',
 'copy',
 'elements',
 'fromkeys',
 'get',
 'items',
 'keys',
 'most_common',
 'pop',
 'popitem',
 'setdefault',
 'subtract',
 'update',
 'values']

In [39]:
c = collections.Counter()                           # a new, empty counter
c
c = collections.Counter({'red': 4, 'blue': 2})      # a new counter from a mapping
c
c = collections.Counter(cats=4, dogs=8)             # a new counter from keyword args
c
c = collections.Counter('gallahad')                 # a new counter from an iterable
c

Counter()

Counter({'red': 4, 'blue': 2})

Counter({'cats': 4, 'dogs': 8})

Counter({'g': 1, 'a': 3, 'l': 2, 'h': 1, 'd': 1})

In [84]:
c.elements()   # repeats same key by count
for i in c.elements():
    print(i)
    
c.keys()
for i in c.keys():
    print(i)
    
c.values()
c.items()

a
a
a
a
b
b


dict_keys(['a', 'b', 'c', 'd'])

a
b
c
d


dict_values([4, 2, 0, -2])

dict_items([('a', 4), ('b', 2), ('c', 0), ('d', -2)])

In [45]:
c.most_common()
c.most_common(3|)

[('a', 3), ('l', 2), ('g', 1), ('h', 1), ('d', 1)]

[('a', 3), ('l', 2), ('g', 1)]

In [77]:
c = collections.Counter(a=4, b=2, c=0, d=-2)
d = collections.Counter(a=1, b=2, c=3, d=4)
#c.subtract(d)
c - d
c + d
c & d

Counter({'a': 3})

Counter({'a': 5, 'b': 4, 'c': 3, 'd': 2})

Counter({'a': 1, 'b': 2})

In [71]:
c
sum(c.values())                 # total of all counts
c.clear()                       # reset all counts
c
c = collections.Counter('Hellooooo!')
list(c)                         # list unique elements
set(c)                          # convert to a set
dict(c)                         # convert to a regular dictionary


Counter({'H': 1, 'e': 1, 'l': 2, 'o': 5, '!': 1})

10

Counter()

['H', 'e', 'l', 'o', '!']

{'!', 'H', 'e', 'l', 'o'}

{'H': 1, 'e': 1, 'l': 2, 'o': 5, '!': 1}

In [76]:
c.items()                       # convert to a list of (elem, cnt) pairs
+c                              # remove zero and negative counts
c

dict_items([('H', 1), ('e', 1), ('l', 2), ('o', 5), ('!', 1)])

Counter({'H': 1, 'e': 1, 'l': 2, 'o': 5, '!': 1})

Counter({'H': 1, 'e': 1, 'l': 2, 'o': 5, '!': 1})

In [86]:
from collections import deque
d = deque('bcd')
d.append('e')   # add a new entry to the right side
d.appendleft('a'); print(d)  # add a new entry to the left side
d.pop(); print(d)
d.popleft(); print(d)
print('---')
print(list(d))
print(d[0])
d.extend('wxwy'); print(d)   # add multiple elements at once
d.rotate(1); print(d)   # rigth rotatoin
d.clear(); print(d)   # empty the deque
d.extendleft('cbaaa'); print(d)  # extendleft() reverses the input order
print(d.count('a'))   # count the # of elements equal to 'a'

deque(['a', 'b', 'c', 'd', 'e'])


'e'

deque(['a', 'b', 'c', 'd'])


'a'

deque(['b', 'c', 'd'])
---
['b', 'c', 'd']
b
deque(['b', 'c', 'd', 'w', 'x', 'w', 'y'])
deque(['y', 'b', 'c', 'd', 'w', 'x', 'w'])
deque([])
deque(['a', 'a', 'a', 'b', 'c'])
3


In [89]:
dir(deque)

['__add__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'appendleft',
 'clear',
 'copy',
 'count',
 'extend',
 'extendleft',
 'index',
 'insert',
 'maxlen',
 'pop',
 'popleft',
 'remove',
 'reverse',
 'rotate']

<div class="alert alert-info" style="font-size:150%">itertools Module</div>

In [123]:
from itertools import *

In [141]:
L = [1, 2, 3]
L2 = ['a','b']
[x for x in accumulate(L)]
[x for x in chain(L, L2)]

[1, 3, 6]

[1, 2, 3, 'a', 'b']

In [149]:
# mask
[x for x in compress(['a','b','c','d','e'], [1,0,1,0,1])]

['a', 'c', 'e']

In [137]:
[x for x in combinations(L, 2)]
[x for x in combinations_with_replacement(L, 2)]
[x for x in permutations(L, 2)]

[(1, 2), (1, 3), (2, 3)]

[(1, 1), (1, 2), (1, 3), (2, 2), (2, 3), (3, 3)]

[(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]

<div class="alert alert-info" style="font-size:150%">random Module</div>

In [96]:
import random

In [109]:
random.randrange(3)   # not inclusive
random.randrange(1, 5, 2)   # not inclusive (start, stop, step)

0

1

In [110]:
random.randint(1, 3)   # inclusive of a, b

3

<div class="alert alert-info" style="font-size:150%">idiom</div>

In [118]:
# finding multiple occurance of max occurance in a list
L = [1, 1, 1, 2, 2, 2, 3, 3, 4, 4, 5]
from collections import Counter
c = collections.Counter(L)
max_no = c.most_common(1)[0][1]
all_list_of_max_freq = [x for x, count in c.most_common() if max_no == count]
all_list_of_max_freq

[1, 2]

In [122]:
# for "distinct" - use (a) set and (b) Counter
digit = 1234567123
set(str(digit))

{'1', '2', '3', '4', '5', '6', '7'}

In [150]:
from itertools import combinations_with_replacement
[x for x in combinations_with_replacement([1, 2, 3], 2)]   

[(1, 1), (1, 2), (1, 3), (2, 2), (2, 3), (3, 3)]

In [10]:
# using lambda
L = [(1, 3), (2, 4), (3, 7)]
L = sorted(L, key=lambda x: x[1])
L

[(1, 3), (2, 4), (3, 7)]

In [13]:
L = [(1, -3), (-2, 4), (-3, 7)]
L = sorted(L, key=lambda x: x[0] * x[1], reverse = True)
L

[(1, -3), (-2, 4), (-3, 7)]

<div class="alert alert-info" style="font-size:150%">General</div>

In [152]:
# you can't really solve floating point - rounding is the best way but rounding also fails
# so use round only when you want to convert to nearest int

from math import sqrt
from decimal import Decimal
for i in range(20):
    print(f'{i:3}:int-{int(sqrt(i)**2):2} {i == int(sqrt(i)**2):<2},round-{round(sqrt(i)**2):2} {i == round(sqrt(i)**2):<2},decimal-{int(Decimal(sqrt(i)**2)):2} {i == int(Decimal(sqrt(i)**2)):<2}')

  0:int- 0 1 ,round- 0 1 ,decimal- 0 1 
  1:int- 1 1 ,round- 1 1 ,decimal- 1 1 
  2:int- 2 1 ,round- 2 1 ,decimal- 2 1 
  3:int- 2 0 ,round- 3 1 ,decimal- 2 0 
  4:int- 4 1 ,round- 4 1 ,decimal- 4 1 
  5:int- 5 1 ,round- 5 1 ,decimal- 5 1 
  6:int- 5 0 ,round- 6 1 ,decimal- 5 0 
  7:int- 7 1 ,round- 7 1 ,decimal- 7 1 
  8:int- 8 1 ,round- 8 1 ,decimal- 8 1 
  9:int- 9 1 ,round- 9 1 ,decimal- 9 1 
 10:int-10 1 ,round-10 1 ,decimal-10 1 
 11:int-11 1 ,round-11 1 ,decimal-11 1 
 12:int-11 0 ,round-12 1 ,decimal-11 0 
 13:int-12 0 ,round-13 1 ,decimal-12 0 
 14:int-14 1 ,round-14 1 ,decimal-14 1 
 15:int-15 1 ,round-15 1 ,decimal-15 1 
 16:int-16 1 ,round-16 1 ,decimal-16 1 
 17:int-17 1 ,round-17 1 ,decimal-17 1 
 18:int-17 0 ,round-18 1 ,decimal-17 0 
 19:int-19 1 ,round-19 1 ,decimal-19 1 


In [163]:
# Remember! set does not keep orders! so when you convert back to list, use sorted(), not list()
L = [138, 583, 868, 822, 783]
list(set(L))
sorted(set(L))

[868, 583, 138, 783, 822]

[138, 583, 783, 822, 868]

<div class="alert alert-info" style="font-size:150%">File Read</div>

In [31]:
filename = 'test_file.txt'
# (1) f.read reads all files in one line
with open(filename, 'r') as f:
    a= f.read()

a
b = a.split('\n')
b


# (2) f.readline() reads one line
# any empty line will be '\n' but the end of line will be ''
with open(filename, 'r') as f:
    f.readline()
    f.readline()
    f.readline()
    f.readline()
    f.readline()
    f.readline()
    f.readline()

"line number 1\n\nskipped line 2 and it's now line 3\nline4 second to last line\nlast line and has an extra space   "

['line number 1',
 '',
 "skipped line 2 and it's now line 3",
 'line4 second to last line',
 'last line and has an extra space   ']

'line number 1\n'

'\n'

"skipped line 2 and it's now line 3\n"

'line4 second to last line\n'

'last line and has an extra space   '

''

''

In [32]:
# (3) effective way to read line by line --- Note '\n' at the end of each line
with open(filename, 'r') as f:
    for line in f:
        line
print('\n')
with open(filename, 'r') as f:
    for line in f:
        line.strip()

'line number 1\n'

'\n'

"skipped line 2 and it's now line 3\n"

'line4 second to last line\n'

'last line and has an extra space   '

'line number 1'

''

"skipped line 2 and it's now line 3"

'line4 second to last line'

'last line and has an extra space'

In [61]:
# (4) reading all the lines into a list --- Note '\n' is included
with open(filename, 'r') as f:
    a = f.readlines()
a
with open(filename, 'r') as f:
    a = list(f)
a

['line number 1\n',
 '\n',
 "skipped line 2 and it's now line 3\n",
 'line4 second to last line\n',
 'last line and has an extra space ']

['line number 1\n',
 '\n',
 "skipped line 2 and it's now line 3\n",
 'line4 second to last line\n',
 'last line and has an extra space ']

In [39]:
import csv

In [40]:
# (5) reading csv file  --- Note there is no '\n' at the end of each line

filename = 'test_file.txt'
with open(filename,'r') as f:
    reader = csv.reader(f)
    for row in reader:
        row


['line number 1']

[]

["skipped line 2 and it's now line 3"]

['line4 second to last line']

['last line and has an extra space   ']

In [36]:
filename = 'monthly_csv.csv'
file_list = []
with open(filename,'r') as f:
    reader = csv.reader(f)
    header_row = next(reader)   # Import to spend the header row
    for row in reader:
        file_list.append(row)
file_list

NameError: name 'csv' is not defined

<div class="alert alert-info" style="font-size:150%">datetime datetime</div>

In [91]:
from datetime import datetime

In [85]:
datetime.today()
a = datetime.now()
# class attribute - so no () at the end
a.year
a.month
a.day
# instance methods
a.date()
a.time()
a.weekday()

datetime.datetime(2018, 9, 3, 10, 12, 22, 516667)

2018

9

3

datetime.date(2018, 9, 3)

datetime.time(10, 12, 22, 518661)

0

In [94]:
d_format = '2016-05-06'
# %a: weekday as Sun, Mon, Tues, etc
# %A: weekday as Sunday, Monday
# %w: weekday as decimal number where 0 is Sunday
# %d: day of month as 01, 02
# %b: month as Jan, Feb
# %B: month as January, February
# %m: month as 01, 02
# %M: minute as 01, 02
# %y: year as 99, 10
# %Y: year as 2010
new = datetime.strptime(d_format, '%Y-%m-%d')
new

datetime.datetime(2016, 5, 6, 0, 0)

<div class="alert alert-info" style="font-size:150%">numpy --- Need MORE!</div>

In [95]:
import numpy as np

In [100]:
np.array([[1,2,3],[4,5,6]], dtype='int64')

array([[1, 2, 3],
       [4, 5, 6]], dtype=int64)

In [113]:
np.array([range(i, i + 3) for i in [2, 4, 6]])
np.zeros(10, dtype=int)
np.random.random((3, 3))

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

array([[0.54220837, 0.56194759, 0.53348949],
       [0.91427151, 0.401706  , 0.68954768],
       [0.07908194, 0.17186225, 0.39488151]])

In [135]:
np.arange(0, 20, 2)

# mgrid is always better
a = np.mgrid[0:5:1, 0:5:1]
a
np.shape(a)

b = np.mgrid[0:5:1]
b
np.shape(b)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

(2, 5, 5)

array([0, 1, 2, 3, 4])

(5,)

One important–and extremely useful–thing to know about array slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.

In [125]:
x = np.array(np.mgrid[0:10:2])
x1 = x[:3]
x1
x1[2] = 9
x


array([0, 2, 4])

array([0, 2, 9, 6, 8])

In [126]:
x = np.array(np.mgrid[0:10:2])
x2 = x[:3].copy()
x2
x2[2] = 9
x

array([0, 2, 4])

array([0, 2, 4, 6, 8])

In [128]:
grid = np.arange(1, 10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
M = np.random.random((3, 4))
M
M.min(axis=0)

array([[0.93272717, 0.27980465, 0.01616996, 0.94132801],
       [0.78955541, 0.46681271, 0.9145175 , 0.72616941],
       [0.95059601, 0.14384723, 0.73179597, 0.20991751]])

array([0.78955541, 0.14384723, 0.01616996, 0.20991751])

In [136]:
x = np.array([1, 2, 3, 4, 5])
x < 3  # less than

array([ True,  True, False, False, False])

In [138]:
x = np.array([11, 12, 13, 14, 45])
ind = [2, 3]
x[ind]

array([13, 14])

In [143]:
# type conversion
L = np.array(['','','23'])
L == ''
L[L=='']='0'
L
L = L.astype(float)
L

array([ True,  True, False])

array(['0', '0', '23'], dtype='<U2')

array([ 0.,  0., 23.])

<div class="alert alert-info" style="font-size:150%">dict</div>

In [146]:
s = [('yellow', 1), ('blue', 2), ('yellow', 3), ('blue', 4), ('red', 1)]   # s is a list of tuples
dict_b = dict()
print(type(dict_b),"---", dict_b)

for k, v in s:
    if k in dict_b:
        dict_b[k].append(v)
    else:
        dict_b[k] = [v]
        
print(type(dict_b.items()),"---", dict_b.items())
print(type(dict_b.values()),"---",dict_b.values())
print(type(dict_b.keys()),"---",dict_b.keys())
print(type(dict_b),"---", dict_b)

<class 'dict'> --- {}
<class 'dict_items'> --- dict_items([('yellow', [1, 3]), ('blue', [2, 4]), ('red', [1])])
<class 'dict_values'> --- dict_values([[1, 3], [2, 4], [1]])
<class 'dict_keys'> --- dict_keys(['yellow', 'blue', 'red'])
<class 'dict'> --- {'yellow': [1, 3], 'blue': [2, 4], 'red': [1]}


In [144]:
s = [('yellow', 1), ('blue', 2), ('yellow', 3), ('blue', 4), ('red', 1)]   # s is a list of tuples
dict_a = dict()
print(type(dict_a),"---", dict_a)

for k, v in s:
    dict_a.setdefault(k, []).append(v)
    # Note: get(key[, default]) won't write to dict. Get only gets the value, but cannot write a (key, value) pair to dict
    # dict_a.get(k,[]).append(v) 
    
print(type(dict_a.items()),"---", dict_a.items())
print(type(dict_a.values()),"---",dict_a.values())
print(type(dict_a.keys()),"---",dict_a.keys())
print(type(dict_a),"---", dict_a)

<class 'dict'> --- {}
<class 'dict_items'> --- dict_items([('yellow', [1, 3]), ('blue', [2, 4]), ('red', [1])])
<class 'dict_values'> --- dict_values([[1, 3], [2, 4], [1]])
<class 'dict_keys'> --- dict_keys(['yellow', 'blue', 'red'])
<class 'dict'> --- {'yellow': [1, 3], 'blue': [2, 4], 'red': [1]}
