In [12]:
# Does not need to be executed if ~/.ipython/profile_default/ipython_config.py
# exists and contains get_config().InteractiveShell.ast_node_interactivity = 'all'

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

<div class="alert alert-info" style="font-size:150%">Quiz 1</div>

<div class="alert alert-info" style="font-size:150%">Quiz 2</div>

if you have an iterable and if you use list comprehension, then you used up the iterable.

When I filter, the results appears to be different each time ---> that's because when you do combinations and do set, the list is not in order.

When you do set = (some list), then order is not guaranteed to be preserved

### sorted() does not modify original but sort does

In [33]:
L = [3 , 2, 1]
sorted(L)
L

[3, 2, 1]

In [34]:
L = [3 , 2, 1]
L =sorted(L)
L

[1, 2, 3]

In [37]:
L = [3 , 2, 1]
L.sort()
L

[1, 2, 3]

In [42]:
L = [(1,2),(3,4),(5,6222)]
min(map(len, L))  


2

In [53]:
abc = min(len(str(x[0])+str(x[1])) for x in L)
print(abc)

2


In [52]:
min(abc)

2

In [55]:
L = [(1,2),(3,4),(5,6222)]

In [56]:
max(x[1] for x in L)

6222

In [74]:
dict1 = dict()

In [60]:
dict1['a'] = [1]

In [61]:
dict1

{'a': [1]}

In [62]:
dict1['a'].append(2)

In [73]:
dict1

{'a': [30, 30]}

In [65]:
'b' in dict1

False

In [93]:
s = {1, 2, 3}
s2 = {3}
s = s - s2

In [107]:
dict1 = {1: [4, 2, 4, 2, 4, 2], 2: [3, 3, 3, 2], 3: [11]}

In [112]:
from collections import Counter
for value in dict1.values():
    value_c = Counter(value)
    print(value_c)
    print(value_c.most_common(1))

Counter({4: 3, 2: 3})
[(4, 3)]
Counter({3: 3, 2: 1})
[(3, 3)]
Counter({11: 1})
[(11, 1)]


<div class="alert alert-info" style="font-size:150%">Quiz 3
</div>

<div class="alert alert-info" style="font-size:150%">Quiz 4

</div>

In [7]:
import itertools
import operator

in Python3, you cannot accept tuples as lambda arguments, so "lambda i, x: ___" doest not work
---https://stackoverflow.com/questions/21892989/what-is-the-good-python3-equivalent-for-auto-tuple-unpacking-in-lambda

In [9]:
# https://docs.python.org/3/library/operator.html
# can be used as a mask or can access certain rows in 2D array
operator.itemgetter(1)('ABCDEFG')

'B'

I should use Pandas groupby sometime

In [50]:
L = [ 1,  4,5,6, 10, 15,16,17,18, 22, 25,26,27,28]
for k, g in itertools.groupby( enumerate(L), lambda x: x[1]-x[0] ) :
  print (list(map(itemgetter(1), g)))

[1]
[4, 5, 6]
[10]
[15, 16, 17, 18]
[22]
[25, 26, 27, 28]


In [54]:
L = [ 1,  4,5,6, 10, 15,16,17,18, 22, 25,26,27,28]
[set(map(itemgetter(1), g)) for k, g in itertools.groupby( enumerate(L), lambda x: x[1]-x[0]) ]


[{1}, {4, 5, 6}, {10}, {15, 16, 17, 18}, {22}, {25, 26, 27, 28}]

In [249]:
# masking
test = [True, False, False, True, True, False, True, True, False, False]
[i  for i, x in enumerate(test) if x]


test1 = np.array(test)

import numpy as np
np.where(test1 == True)
np.where(test1)

# problem with above is that it creates tuples of tuples...
np.arange(10)[test1]


[0, 3, 4, 6, 7]

(array([0, 3, 4, 6, 7], dtype=int64),)

(array([0, 3, 4, 6, 7], dtype=int64),)

array([0, 3, 4, 6, 7])

In [318]:
# you can iterate backwards with:
L = [1, 2, 3]
for i, x in enumerate(L[::-1]):
    print(i, x)

0 3
1 2
2 1


In [5]:
from random import seed, randrange
import sys
import numpy as np
import itertools
import operator




def count_blocks(dim, for_seed, n):
    seed(for_seed)
    grid = [[bool(randrange(n)) for _ in range(dim)] for _ in range(dim)]
    grid_np = np.array(grid)

    # ones is a matrix of each row showing indices where grid == True
    ones = []
    for row in grid_np:
        ones.append(np.arange(dim)[row])

    # consecutive_ones is a matrix of each row showing a list of sets of consecutive numbers
    consecutive_ones = []
    for row in ones:
        L = row.tolist()
        consecutive_ones.append([set(map(operator.itemgetter(1), g)) for k, g in itertools.groupby( enumerate(L), lambda x: x[1]-x[0])])

    max_block = 0
    for row in range(dim - 1, -1, -1):   # count backwards
        for x in consecutive_ones[row]:
            temp = x
            block = len(temp)
            # look up the stack
            for row2 in range(row - 1, -1, -1):
                temp = temp & set(ones[row2])
                if len(temp) == 0:
                    break
                block += len(temp)
            max_block = max(max_block, block)
    return max_block

            
def print_result():
    print(f'dim: {dim}, for_seed: {for_seed}, n: {n} ==> max_block is {max_block}')

    
dim = 10
for t1 in range(0, 10):
    for_seed = t1
    for t2 in range(0, 20):
        n = t2        
        ### code here ####
        ### max_block is my version of total number of blocks
        print(f'dim: {dim}, for_seed: {for_seed}, n: {n} ==> max_block is {max_block}')
            
            

ValueError: empty range for randrange()

<button class="btn btn-primary btn-lg btn-block">Redo</button>

<div class="alert alert-info" style="font-size:150%">Quiz 1 - Redo - 1 hour</div>

In [2]:
import sys
from random import seed, randrange
    
arg_for_seed = 105

seed(arg_for_seed)
x = randrange(10 ** 10)
L = [randrange(10 ** 8) for _ in range(10)]



### My Code ###
### 1: sum of digits in x
x1 = list(str(x))
sum_of_digits_in_x = sum([int(k) for k in x1])
sum_of_digits_in_x

### 2: compare first and last digit
first_digit_greater_than_last = 0
same_first_and_last_digits = 0
last_digit_greater_than_first = 0

for num in L:
    fd = int(str(num)[0])
    ld = int(str(num)[-1])
    first_digit_greater_than_last += 1 * (fd > ld)
    same_first_and_last_digits += 1 * (fd == ld)
    last_digit_greater_than_first += 1 * (fd < ld)

first_digit_greater_than_last
same_first_and_last_digits
last_digit_greater_than_first

### 3: distinct digits
distinct_digits = [0] * 9

from collections import Counter

# method 1: method 1 only goes through loop once
for num in L:
    dd = len(list(Counter(str(num)).keys()))   # distinct digit
    distinct_digits[dd] += 1

print(L)
    
# method 2: Original method. Takes longer but uses set.
c =   Counter(len(set(str(item))) for item in L)
for i in c:
    distinct_digits[i]= c[i]
    
###*********************************************************************************
#best method is to use set() to count distinct but uses method 1 to use only one loop
###*******************************************************************************    
    
distinct_digits

### 4: min/max gap
# ---- I originally created a list of gap which is inferior
min_gap = 10
max_gap = -1

for num in L:
    fd = int(str(num)[0])
    ld = int(str(num)[-1])
    gap = abs(fd - ld)
    min_gap = min(min_gap, gap)
    max_gap = max(max_gap, gap)
    
min_gap
max_gap

### 5: (f, l) pairs # of times occurring
### ------------Note: Counter.most_common() won't find all the lsit of most occurances...
### ----- my first implementation is same as this one without using numpy

import numpy as np

first_and_last = set()

fl = []
for num in L:
    fl.append((int(str(num)[0]), int(str(num)[-1])))


fl_c = Counter(fl)
no_times_most_common = fl_c.most_common()[0][1]


# method 1
most_common = np.array(fl_c.most_common())

for k in most_common:
    if k[1] == no_times_most_common:
        first_and_last.add(k[0])
        
# **************************
# better method
# **************************
# method 2
first_and_last = set(k for k, count in fl_c.most_common() if count == no_times_most_common)
first_and_last



[266286, 41905292, 70335023, 76567783, 44922498, 39290063, 21983326, 46748446, 22233298, 19806125]


{(2, 6), (7, 3)}

<div class="alert alert-info" style="font-size:150%">Quiz 2 - Redo - 2 hours</div>

In [7]:
import sys
from random import seed, randint
from math import gcd

arg_for_seed = 1
length = 10
max_value = 10
    
seed(arg_for_seed)
L = [randint(1, max_value) for _ in range(length)]
print('Here is L:')
print(L)


### My Code

from itertools import combinations_with_replacement
from collections import Counter


### (1) finding simple and complex fractions

#*********************************--------------------------
# Very important--------------------------------------------
# when you convert back from set to list, use sorted() as list() does not preserve order
#-----------------------------------------------------------------------------
#********************************
L = sorted(set(L)) 
# print('Here is L:')
# print(L)

fractions = [x for x in combinations_with_replacement(L, 2)]
fractions
# print(fractions)
# simplify fraction
fractions = [( round( x[0] / (gcd(x[0],x[1]))) , round( x[1] / (gcd(x[0],x[1])))) for x in fractions]

# print(fractions)
len_of_fractions = [ len(str(x[0])+str(x[1])) for x in fractions]


#--------------------------------------------------------------------------
# as I did it in the first time, it's more efficient to do combinations and just add (1, 1) at the end
# b/c "with_replacement" only adds (1, 1) case
#---------------------------------------------------------------------------



size_of_simplest_fraction = min(len_of_fractions)
size_of_most_complex_fraction = max(len_of_fractions)

simplest_fractions = [x for x in fractions if len(str(x[0])+str(x[1])) == size_of_simplest_fraction]
simplest_fractions = list(set(simplest_fractions))
simplest_fractions = sorted(simplest_fractions, key=lambda x: x[0] / x[1])
most_complex_fractions = [x for x in fractions if len(str(x[0])+str(x[1])) == size_of_most_complex_fraction]
most_complex_fractions = list(set(most_complex_fractions))
most_complex_fractions = sorted(most_complex_fractions, key=lambda x: x[0] / x[1], reverse=True)

#print(simplest_fractions)
#print(most_complex_fractions)

### (2) finding multiplicity of prime factors

# ------------------------------------------------------------------
# Note: "multiplicity" should be the Ah-ha! momement to use Counter
# ------------------------------------------------------------------

L = [x[1] for x in most_complex_fractions]

#-------------------------------------------------------------
# this is probably the best algorithm
#------------------------------------------------------------

primes_list = []
for x in L:
    # factors out primes one by one allowing for multiplicity
    primes = []
    i = 2
    while (i <= x):
        while (x % i == 0):
            x //= i
            primes.append(i)
        i += 1
    
    primes_list.append(Counter(primes))


if bool(primes_list[0]) == False:
    multiplicity_of_largest_prime_factor = 0
    largest_prime_factors = []
else:
    multiplicity_of_largest_prime_factor = max([x.most_common(1)[0][1] for x in primes_list])
    #-----------------------------------------------------------
    # note below for multiple occurence of max    
    #------------------------------------------------------------
    largest_prime_factors = [y for x in primes_list for y, count in x.most_common() if count == multiplicity_of_largest_prime_factor]
    largest_prime_factors  = sorted(set(largest_prime_factors)) 



Here is L:
[3, 10, 2, 5, 2, 8, 8, 8, 7, 4]


[(2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 7),
 (2, 8),
 (2, 10),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 7),
 (3, 8),
 (3, 10),
 (4, 4),
 (4, 5),
 (4, 7),
 (4, 8),
 (4, 10),
 (5, 5),
 (5, 7),
 (5, 8),
 (5, 10),
 (7, 7),
 (7, 8),
 (7, 10),
 (8, 8),
 (8, 10),
 (10, 10)]

<div class="alert alert-info" style="font-size:150%">Quiz 3 - Redo - 2 hours</div>

In [156]:
import sys, os
import csv

filename = 'monthly_csv.csv'
if not os.path.exists(filename):
    print(f'There is no file named {filename} in the working directory, giving up...')
    sys.exit()
    
source = 'GISTEMP' # 'GCAG' # 'GISTEMP'
year_or_range_of_years = ' 1983 -- 1958   '
month = 'January'
average = 0
years_above_average = []

### My Code ###########################################

import numpy as np
from datetime import datetime

### (1) checking input format

year_or_range_of_years = year_or_range_of_years.strip()
years_list = year_or_range_of_years.split("--")

if '' in years_list:
    sys.exit()

years_list = sorted(set([int(x.strip()) for x in years_list]))   # recall idiom to get distinct elements sorted
year1 = years_list[0]
#----------
# originally, I tested if the years are the same, but this is better
year2 = years_list[-1]


months = {'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5, 'June': 6, 'July': 7, 'August': 8, 'September': 9, 'October': 10, 'November': 11, 'December': 12}

if month not in months:
    sys.exit()
    
sources = ('GCAG', 'GISTEMP')

if source not in sources:
    sys.exit()

### (2) reading file

GCAG = []
GISTEMP = []
#-----------------------------------
# my original solution was good as below
#-----------------------------------
sources = {'GCAG': GCAG ,'GISTEMP': GISTEMP}


with open(filename, 'r') as f:
    reader = csv.reader(f)
    header = next(reader)    
    for row in reader:
        sources[row[0]].append([datetime.strptime(row[1], '%Y-%m-%d'), float(row[2])])
        
#####################################################################
#  --- I need to figure out how to fo filture in numpy later
#-----------------------------------------------
#--------This was hard---overall, let's not use numpy until the end
# I ended up using my original code
##################################################################
filtered = np.array([x for x in sources[source] if x[0].year >= year1 and x[0].year <= year2 and x[0].month == months[month]])
average = np.mean(filtered[:,1])   # no need to use statistics module
        
years_above_average = sorted([x[0].year for x in filtered if x[1] > average])
average
years_above_average



0.0676923076923077

[1958, 1961, 1962, 1970, 1973, 1975, 1977, 1978, 1979, 1980, 1981, 1982, 1983]

In [15]:
import csv
filename = 'monthly_csv.csv'
with open(filename, 'r') as f:
    reader = csv.reader(f)
    header = next(reader)
    next(reader)
    next(reader)
    next(reader)
    next(reader)

header

['GCAG', '2016-12-06', '0.7895']

['GISTEMP', '2016-12-06', '0.81']

['GCAG', '2016-11-06', '0.7504']

['GISTEMP', '2016-11-06', '0.93']

['Source', 'Date', 'Mean']